// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as WrapJs from "./wrap.js";
import ReactDraggableList from "react-draggable-list";

function wrap(prim) {
  return WrapJs.wrap(prim);
}

var Template = {
  wrap: wrap
};

function makeProps(items, itemKey, template, onMoveEnd, container, springConfig, padding, unsetZIndex, constrainDrag, autoScrollMaxSpeed, commonProps, param) {
  return {
          list: items,
          itemKey: itemKey,
          template: WrapJs.wrap(template),
          onMoveEnd: onMoveEnd,
          container: container,
          springConfig: springConfig,
          padding: padding,
          unsetZIndex: unsetZIndex,
          constrainDrag: constrainDrag,
          autoScrollMaxSpeed: autoScrollMaxSpeed,
          commonProps: commonProps
        };
}

function make(props) {
  return React.createElement(ReactDraggableList, props);
}

export {
  Template ,
  makeProps ,
  make ,
  
}
/* react Not a pure module */
